# The rate for the proxy to run at
rate: 30
# The ip of the roborio/networktables server (should be static)
server_ip: "10.06.24.2"
# The networktables table name
table_name: "SmartDashboard"

# Wanted Output Data ("number", "string", "boolean")
output_data: [{name: "/pathTable/startPathIndex", type: "number", default: -1.0}]

# Wanted Input Data ("number", "string", "boolean")
input_data: [{name: "/auto/state", type: "boolean", default: false}, 
             {name: "/auto/select", type: "number", default: 0.0},
             {name: "/pathTable/status/path", type: "number", default: 0.0},
             {name: "/pathTable/status/point", type: "number", default: 0.0},
             {name: "/pathTable/status/finishedPath", type: "string", default: "false 0"},
             {name: "/pose/th", type: "number", default: 0.0},
             {name: "/pose/x", type: "number", default: 0.0},
             {name: "/pose/y", type: "number", default: 0.0}]